Add external OpenID login
DefGuard/defguard pull request #676
Opened 2024-07-15 11:35 UTC by t-aleksander

## 📖 Description

1. include a **summary of the changes and the related issue**, eg. _Closes #XYZ_
2. Do not make a PR if you can't check **all the boxes below**

### 🛠️ Dev Branch Merge Checklist:

#### Documentation ###

- [ ] If testing requires changes in the environment or deployment, please **update the documentation** (https://defguard.gitbook.io) first and **attach the link to the documentation** section in this pool request
- [ ] I have commented on my code, particularly in hard-to-understand areas

#### Testing ### 

- [ ] I have prepared end-to-end tests for all new functionalities
- [ ] I have performed end-to-end tests manually and they work
- [ ] New and existing unit tests pass locally with my changes

#### Deployment ###

- [ ] If deployment is affected I have made corresponding/required changes to [deployment](https://github.com/defguard/deployment) (Docker, Kubernetes, one-line install)

### 🏚️ Main Branch Merge Checklist:

#### Testing ### 

- [ ] I have merged my changes before to dev and the dev checklist is done
- [ ] I have tested all functionalities on the dev instance and they work

#### Documentation ###

- [ ] I have made corresponding changes to the **user & admin documentation** and added new features documentation with screenshots for users/admins

2024-07-16 13:15 UTC, teon commented on LICENSE
> +Note: The following license applies to the entire repository except for the "enterprise" directory.
NOTE: The following license applies to the entire repository except for all the contents in the "enterprise" directory in this repository.
NOTE: For the license of the enterprise directory, go to enterprise/LICENSE.

2024-07-16 13:16 UTC, teon commented on src/enterprise/LICENSE
> +Files in this directory ("enterprise") are not under the default repository license. Contact sales<at>defguard.net for further information.
For enterprise license and usage of this code & binary distribution with this code please contact by email: sales<at>defguard.net

2024-07-17 10:25 UTC, j-chmielewski requested changes

2024-07-17 10:25 UTC, j-chmielewski commented on src/enterprise/handlers/openid_login.rs
> +        let metadata = get_provider_metadata("https://accounts.google.com")
Don't perform network queries in unit tests.

2024-07-17 10:25 UTC, j-chmielewski commented on src/enterprise/handlers/openid_providers.rs
> +    pub fn new(name: String, base_url: String, client_id: String, client_secret: String) -> Self {
take &str instead of String

2024-07-17 10:25 UTC, j-chmielewski commented on web/src/pages/auth/Login/components/OidcButtons.tsx
> +const GoogleButton = ({ url }: { url: string }) => {
How does this work with any other oidc provider?

2024-07-17 10:25 UTC, j-chmielewski commented on web/src/pages/users/UserProfile/UserProfile.tsx
> +            console.log('submitSubject.next();');
Delet dis

2024-07-17 10:25 UTC, j-chmielewski commented on src/lib.rs
> +            .route("/openid/auth_info", get(get_auth_info)),
`delete_openid_provider`, `modify_openid_provider`

2024-08-05 17:09 UTC, merged